### ISSUE TITLE
Add more data sets to data set table

### ISSUE THREAD

**Issue by gplssm** [gplssm/egon-website#28]
Right now, only _medium-voltage grid districts_ appears in the [data set table](https://github.com/gplssm/egon-website/blob/dev/_data/openego_data.yml). Decide on which data sets should be added and add them.

Ideas from @gplssm

- osmTGmod transmission grid model
- ...

**Comment by IlkaCu** [comment]
I would suggest to add the following tables (mainly tables with a HV/EHV focus): 

**Demand/Supply**
- demand.ego_dp_loadarea 
- supply.ego_dp_conv_powerplant
- supply.ego_dp_res_powerplant

**eTraGo-model**
- grid.ego_pf_hv_bus
- grid.ego_pf_hv_generator
- grid.ego_pf_hv_generator_pq_set
- grid.ego_pf_hv_load
- grid.ego_pf_hv_load_pq_set
- grid.ego_pf_hv_storage
- grid.ego_pf_hv_transformer
- grid.ego_pf_hv_line

**osmTGmod-model**
- otg_ehvhv_branch_data 	
- otg_ehvhv_bus_data 	
- otg_ehvhv_dcline_data

@gplssm Is it possible to cluster entries in the data set table?

**Comment by gplssm** [comment]
Perfect! Let's take these data sets for now. We can add more anytime.

On the example of Demand/Supply, a entry with multiple tables should look like this in the [data .yml file](https://github.com/gplssm/egon-website/blob/4817e2cb5db8bb601d3d232550d367b62674278d/_data/openego_data.yml)

```
- dataset: Demand/Supply
  description: <description>
  tables:
    - name: "demand.ego_dp_loadarea"
      url: https://openenergy-platform.org/dataedit/view/demand/ego_dp_loadarea
    - name: "supply.ego_dp_conv_powerplant"
      url: https://openenergy-platform.org/dataedit/view/supply/ego_dp_conv_powerplant
  license:
    name: Open Data Commons Open Database License 1.0
    copyright: © Reiner Lemoine Institut
    acronym: ODbL-1.0
    url: https://opendatacommons.org/licenses/odbl/1.0/
```

I guess @KathiEsterl adds the datasets... If you have questions, feel free to ask. I can review the PR, once it's done
